name: glow_container
description: "A highly customizable Flutter widget that enhances a rectangular container with an animated glowing border effect."
version: 0.0.1
homepage: https://github.com/thomasporro/glow_container
repository: https://github.com/thomasporro/glow_container
issue_tracker: https://github.com/thomasporro/glow_container/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
screenshots:
  - description: 'Showcase of the glow container'
    path: /example/screenshots/glow_container.gif

environment:
  sdk: ^3.4.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
